# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3961ee8fe99acb689388f293b1a36c925928f18cad0c6e31a4a220251e09fd054da6a20f061d9d0994611e341b43ec1d6eec3c6d537c3e52786bad9c51feface

test:
  secret_key_base: c242e1313db6a78d33d317e1a43f46ed641edc371b2e6650b693afaab5fe73cfa8d2f111b5ab67ef0fd6e7b4985bbc2abdd6727ee531dd70894a31977a2b4401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
